"""Build the seed dataset: stitch OSM/Wikidata coordinates to Wikipedia stories.

Run once, review the diff, commit the output. This is a batch job -- the
serving API never calls OpenStreetMap or Wikipedia.

    python -m ingestion.build_seed [--limit N] [--no-overpass] [--only ID ...]

Pipeline, per curated entry in ``ingestion/seed_places.yaml``:

1. **Where.** Resolve the Wikipedia article to get its coordinates and its
   Wikidata item. Fall back to the Wikidata P625 property if the article has
   no coordinates.
2. **Base layer.** Ask Overpass for the OSM element carrying that Wikidata
   ID. When found, OSM's coordinates and IDs win -- OSM is the base layer,
   and its provenance goes into the record. When not found, the Wikidata
   coordinates stand and ``osm_id`` stays null.
3. **Story.** Match the place to an article via ``ingestion.match`` and store
   the lead-section extract with full attribution. No confident match means
   an empty ``stories`` list, never a guessed one.

Output: one ``data/places/<id>.yaml`` per place, which is also the file
format contributors edit by hand.
"""

from __future__ import annotations

import argparse
import logging
import sys
from datetime import date
from pathlib import Path

import yaml

from ingestion.match import match_article
from ingestion.sources import osm
from ingestion.sources.wikipedia import LICENSE, WikipediaClient

logger = logging.getLogger("build_seed")

ROOT = Path(__file__).resolve().parent.parent
SEED_FILE = ROOT / "ingestion" / "seed_places.yaml"
OUT_DIR = ROOT / "data" / "places"


def load_seed() -> list[dict]:
    with SEED_FILE.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)["places"]


def write_place(record: dict) -> Path:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / f"{record['id']}.yaml"
    with path.open("w", encoding="utf-8") as fh:
        fh.write(
            "# Generated by `python -m ingestion.build_seed`, then reviewed by a human.\n"
            "# Hand edits are welcome and are preserved -- see CONTRIBUTING.md.\n"
        )
        yaml.safe_dump(record, fh, allow_unicode=True, sort_keys=False, width=100)
    return path


def build(entries: list[dict], use_overpass: bool = True) -> dict:
    client = WikipediaClient()
    report = {"written": 0, "story_less": 0, "skipped": [], "osm_backed": 0}

    try:
        # Step 1: where.
        resolved: list[dict] = []
        for entry in entries:
            title = entry.get("wikipedia_title") or entry["name"]
            article = client.fetch_article(title)
            if article is None:
                logger.warning("skipping %s: no Wikipedia article for %r", entry["id"], title)
                report["skipped"].append({"id": entry["id"], "reason": "no article"})
                continue
            resolved.append({"entry": entry, "article": article})

        # Coordinates the article did not carry, straight from Wikidata.
        missing_coords = [
            r["article"].wikidata_id
            for r in resolved
            if r["article"].lat is None and r["article"].wikidata_id
        ]
        wikidata_coords = osm.fetch_wikidata_coordinates(missing_coords) if missing_coords else {}

        # Step 2: base layer from OSM.
        qids = [r["article"].wikidata_id for r in resolved if r["article"].wikidata_id]
        osm_pois: dict[str, osm.OsmPoi] = {}
        if use_overpass and qids:
            try:
                osm_pois = osm.fetch_by_wikidata(qids)
            except Exception:
                logger.warning(
                    "Overpass unavailable; falling back to Wikidata coordinates", exc_info=True
                )

        # Step 3: story.
        for item in resolved:
            entry, article = item["entry"], item["article"]
            qid = article.wikidata_id
            poi = osm_pois.get(qid) if qid else None

            if poi is not None:
                lat, lon = poi.lat, poi.lon
                report["osm_backed"] += 1
            elif article.lat is not None:
                lat, lon = article.lat, article.lon
            elif qid in wikidata_coords:
                lat, lon = wikidata_coords[qid]
            else:
                logger.warning("skipping %s: no coordinates from any source", entry["id"])
                report["skipped"].append({"id": entry["id"], "reason": "no coordinates"})
                continue

            match = match_article(
                client,
                name=entry["name"],
                lat=lat,
                lon=lon,
                explicit_title=entry.get("wikipedia_title"),
            )

            stories = []
            if match is not None:
                stories.append(
                    {
                        "title": match.article.title,
                        "body_md": match.article.extract,
                        "lang": "en",
                        "source_name": "Wikipedia",
                        "source_url": match.article.url,
                        "license": LICENSE,
                        "retrieved_at": date.today().isoformat(),
                        "match_method": match.method,
                        "match_confidence": match.confidence,
                    }
                )
            else:
                report["story_less"] += 1

            # A "local" name identical to the English one carries nothing.
            local_name = (poi.name_local if poi else None) or entry.get("name_local")
            if local_name == entry["name"]:
                local_name = None

            record = {
                "id": entry["id"],
                "name": entry["name"],
                "name_local": local_name,
                "category": entry["category"],
                "lat": round(lat, 6),
                "lon": round(lon, 6),
                "address": entry.get("address"),
                "city": entry.get("city"),
                "state": entry.get("state"),
                "osm_type": poi.osm_type if poi else None,
                "osm_id": poi.osm_id if poi else None,
                "wikidata_id": qid,
                "wikipedia_title": entry.get("wikipedia_title"),
                "stories": stories,
            }
            write_place(record)
            report["written"] += 1
    finally:
        client.close()

    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit", type=int, help="Only process the first N entries.")
    parser.add_argument("--only", nargs="*", help="Only process these place IDs.")
    parser.add_argument(
        "--no-overpass",
        action="store_true",
        help="Skip OpenStreetMap and use Wikidata coordinates only.",
    )
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s %(name)s: %(message)s",
    )

    entries = load_seed()
    if args.only:
        wanted = set(args.only)
        entries = [e for e in entries if e["id"] in wanted]
    if args.limit:
        entries = entries[: args.limit]

    report = build(entries, use_overpass=not args.no_overpass)

    print(
        f"\nwritten:        {report['written']}"
        f"\nOSM-backed:     {report['osm_backed']}"
        f"\nstory-less:     {report['story_less']}"
        f"\nskipped:        {len(report['skipped'])}"
    )
    for item in report["skipped"]:
        print(f"  - {item['id']}: {item['reason']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
